apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: springboot-http
  namespace: demo
spec:
  scaleTargetRef:
    name: springboot-demo         # Deployment name
    service: springboot-demo      # Service name
    port: 80                   # Service port

  replicas:
    min: 1
    max: 2

  targetPendingRequests: 0
