apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-cache-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/sanjeev/k8s-volumes/maven-cache