replicaCount: 1

image:
  repository: docker.io/sanjeevk95/springboot-demo
  tag: 47
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

